package(default_visibility = ["//visibility:public"])

filegroup(
    name = "swig_includes",
    srcs = glob(["*.i"]),
)

filegroup(
    name = "swig_file_appender",
    srcs = ["swig_file_appender.py"],
)
