name: Add Module

on:
  workflow_call:
    inputs:
      module_name:
        description: 'Name of module to update.'
        required: true
        type: string
      version:
        description: 'Version to add. Expected to match a tag in the repo.'
        required: true
        type: string
concurrency: 
  group: ${{ github.ref }}
jobs:
  update-module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Index Registry
        uses: actions/checkout@v3
        with:
          repository: "pattern-labs/index-registry"

      - name: Run Script; Adds Module
        run: python3 .github/workflows/tools/main.py --index --add-module ${{ inputs.module_name }} ${{ inputs.version }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github.actor
          push: origin ${{ steps.branch-name.outputs.current_branch }} --set-upstream
          message: 'Adds ${{ inputs.module_name }}@${{ inputs.version }}.'
          add: '["modules/${{ inputs.module_name }}/metadata.json", 
                "modules/${{ inputs.module_name }}/${{ inputs.version }}/MODULE.bazel",
                "modules/${{ inputs.module_name }}/${{ inputs.version }}/source.json"]'
          
