name: Bump Minor

on:
   workflow_call:
    inputs:
      module_name:
        description: 'Name of module to update.'
        required: true
        type: string

jobs:
  bump-minor:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Index Registry
        uses: actions/checkout@v3
        with:
          repository: "pattern-labs/index-registry"

      - name: Checkout Repo being bumped
        uses: actions/checkout@v3
        with:
          repository: "pattern-labs/${{ inputs.version }}"
          path: local_repo
          token: ${{ secrets.REPO_ACCESS_PAT }}

      - name: Set Repo PAT
        run: export PATTERN_GITHUB_TOKEN=${{ secrets.REPO_ACCESS_PAT }}

      - name: Update BAZEL.module
        run: python3 .github/workflows/tools/main.py --local --bump-minor --export-tag --save-local

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github.actor
          push: origin ${{ steps.branch-name.outputs.current_branch }} --set-upstream --force
          message: 'Update bazel tag to ${{ env.PATTERN_VERSION_NUMBER }}".'
          add: "MODULE.bazel"
          tag:  ${{ env.PATTERN_VERSION_NUMBER }}
          tag_push: '--force'
          
