name: Call Bump Version

on:
   workflow_dispatch:
    inputs:
      module_name:
        description: 'Name of module to update.'
        required: true
        type: string
      bump_type:
        description: 'Name of module to update.'
        required: true
        default: 'minor'
        type: choice
        options:
        - minor
        - patch

jobs:
  call-bump-version:
    uses: pattern-labs/index-registry/.github/workflows/bump_version.yml@eng/better-rules
    with:
      module_name: ${{ github.event.inputs.module_name }}
      bump_type: ${{ github.event.inputs.bump_type }}
    secrets: inherit
