name: Update Dependency

on:
   workflow_call:
    inputs:
      dependent:
        description: 'Dependent being updated.'
        required: true
        type: string
      dependency:
        description: 'Dependency being updated.'
        required: true
        type: string
      version:
        description: 'Version of dependency.'
        required: true
        type: string
concurrency: 
  group: ${{ github.ref }}

jobs:
  bump-patch:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Index Registry
        uses: actions/checkout@v3
        with:
          repository: "pattern-labs/index-registry"

      - name: Checkout Repo being bumped
        uses: actions/checkout@v3
        with:
          repository: "pattern-labs/${{ inputs.dependent }}"
          path: local_repo
          token: ${{ secrets.REPO_ACCESS_PAT }}
          fetch-depth: 0

      - name: Set Repo PAT
        run: export PATTERN_GITHUB_TOKEN=${{ secrets.REPO_ACCESS_PAT }}

      - name: Update Dependency
        run: python3 .github/workflows/tools/main.py --local --update-dependency ${{ inputs.dependency }} ${{ inputs.version }} --save-local --module-name ${{ inputs.dependent }}

      - name: Bump Patch
        run: python3 .github/workflows/tools/main.py --local --bump-minor --export-tag --save-local --module-name ${{ inputs.dependent }}
      
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ./local_repo
          author_name: github.actor
          message: 'Update dependency ${{ inputs.dependency }} to ${{ inputs.version }} and version to ${{ env.PATTERN_VERSION_NUMBER }}".'
          add: "MODULE.bazel"
          tag:  ${{ env.PATTERN_VERSION_NUMBER }}
          tag_push: '--force'
